version: '3'

services:

  redis:
    image: redis
    ports:
      - "6380:6379"

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /var/lib/postgresql/data/pgdata

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    depends_on:
      - db

  celery: # Запуск celery
    build: . # Откуда
    tty: true
    command: celery -A config worker -l INFO
    depends_on:
      - redis
      - app

  celery-beat:
    build: .
    tty: true
    command: celery -A config beat -l INFO -S django
    depends_on:
      - redis
      - app
